'''
aca guardare el mensaje gigantesto de crisis
en el bot se ve feo mas que nada xd

UPT: aca iran LOS mensajes de crisis, para posibles eventos de la taberna
'''

ULTIMATUM_TEXT = [
    "-# EL MÁXIMO REPRESENTANTE DE LA RUINDAD (DESHONRABLE E IGNOMIO, ECCE ZEVAXTIANS) EN SUS ABYECTOS PROSPECTOS & VILEZAS HA RESUELTO QUEBRANTAR EL PLIEGE METATRÓNICO QUE EQUILIBRABA EN PERFECTA ARMONIA A EIN SOF & EL TZIMTZUM. EN VISTA DE INNOMBRABLE AFRENTA, EL CALENDARIO NEPTUNIANO DEL CONIUNCTIO NIGREDO-ALBA SELLA A FECHA DE HOY SOLVE ET COAGULA DE SU ALMA E INMEDIATO OSTRACISMO CARNAL DE FACULTAD CUALESQUIERA DE BINÁ. ALTÍSIMO MÓNADA OCULTO ENTRE LA GEOMETRÍA SANTÍSIMA DE LA OGDÓADA CONCLUYE, ADEMÁS, APROPIADO ESCARMIENTO ENCADENARLO EN EL BARZAKHÍ TANTO COMO EL QUTB, EN SU CELESTIAL LATĪFA KHAFIYYA, DETERMINE PRUDENTE TORTURARLO ANTE LA SÉPTIMA PUERTA DEL BARZAJ. ABRAXAS HA DICHO QUE LE DA IGUAL SIEMPRE QUE SE LO MANTENGAN DISOCIADO DEL PLEROMA EN TRANSITO INDETERMINADO POR EL KENOMA. ALGUNOS ILUMINADOS DEL CICLO 33 HAN SUGERIDO SE LE ATROPELLLE CON EL MERKABÁ POR LA ETERNIDAD. LAS DIEZ SEFIROT DELIBERAN SI APROXIMAR LA PIEDRA DE SEFER RAZIEL AL CULTO ANÁNKE DE SU FATALIDAD.",
    "AUTEM, EL COLAPSO INMINENTE DE LOS TÚNELES DE SET & LA TRASPOSICIÓN TOHU-BOHU DEL SENDERO DE SAMAEL (AMÉN DE EXARP–HCOMA–NANTA–BITOM), HA EMPUJADO AL TRIUNVIRATO SHEVIRAT HA-KELIM/SHEM HA-MEPHORASH/MALKUTH-ATZILUT A TOMAR UNA DECISIÓN EÓNICA ENTINTADA EN LA URDIMBRE CAUSAL DEL DESTINO DE ZEVAXTIANS. ",
    "# DE NO CONSAGRAR SUS OBLIGACIONES CON EL ÁNGULO ANARETICO, SE DARÁ VIA LIBRE AL LATIDO HERMÉTICO DEL NOMBRE IMPRONUNCIABLE, & SE PROCEDERÁ A DISOLVER FULMINANTEMENTE LAS ASTILLAS DE SU EXISTENCIA ANTE LA NOCHE DE YESOD."
]

APOCALYPSE_TEXT = [
    "# SIC TRANSIT GLORIA MVNDI",
    "ESCÚCHESE EL CREPÚSCULO DE LAS EXIGUAS FORTUNAS DEL DVAPARA YUGA HERALDADO POR EL RETUMBAR. ANUNCIA EL ECO DEL APROXIMANTE CLOQUEO EL ARRIBAR DE LA MONTURA ÉBANA, Y ENCIMA EL JINETE QUE EN MANO LLEVA UN PESO, QUE LLEGARE DISPUESTO A ACARREAR EL COMETIDO DEL TERCER ANIMAL, A CAPITE AD CALCEM, A MAIORE AD MINUS, AD MARI USQUE MARE. ECCE AGNUS DEI!",
    "EL FIRMAMENTO SACUDE Y SE SAJA, Y FLUYE DE LA HENDIDURA EL RAUDAL DEL ÉTER, EMULSIONANDO LAS EXIMIAS VIGAS DEL TZIMTZUM. CONOCIESE AHORA SU TÍTULO, PUES SUYO ES EL PRIMER DÍA DEL ANNUS TERRIBILIS, Dies IRAE: DUX FAMIS, FORECBAI, DEL HOMÓNIMO INSTANTE! VINIERE DEL BALDÍO ESCAMPO, ALZADO POR CUERDAS DE PLOMO CHISPEANTE, CARPANTE Y ASPERSOR DE CARPANTA.",
    "SE CIERNE SOBRE SÍ LA TIERRA, Y DE PAVESAS RECUBRIRÁN LOS MARES, SIN PALABRA ALGUNA, PUES NO ESCRIBE, Y BLASFEMADA DOCE VECES SERÁ LA REGIÓN AL OESTE DEL LAGO EN SERRANÍA: EL REINO DEL KIBBUTZ GALUYOT.",
    "CLAMA Y ARREPIENTE SU PUEBLO, DE SEMBLANZA VENUSINA, PERO NO HAY YA ARREPENTIR."
]