'''
aca guardare el mensaje gigantesto de crisis
en el bot se ve feo mas que nada xd
'''

ULTIMATUM_TEXT = [
    "-# EL MÁXIMO REPRESENTANTE DE LA RUINDAD (DESHONRABLE E IGNOMIO, ECCE ZEVAXTIANS) EN SUS ABYECTOS PROSPECTOS & VILEZAS HA RESUELTO QUEBRANTAR EL PLIEGE METATRÓNICO QUE EQUILIBRABA EN PERFECTA ARMONIA A EIN SOF & EL TZIMTZUM. EN VISTA DE INNOMBRABLE AFRENTA, EL CALENDARIO NEPTUNIANO DEL CONIUNCTIO NIGREDO-ALBA SELLA A FECHA DE HOY SOLVE ET COAGULA DE SU ALMA E INMEDIATO OSTRACISMO CARNAL DE FACULTAD CUALESQUIERA DE BINÁ. ALTÍSIMO MÓNADA OCULTO ENTRE LA GEOMETRÍA SANTÍSIMA DE LA OGDÓADA CONCLUYE, ADEMÁS, APROPIADO ESCARMIENTO ENCADENARLO EN EL BARZAKHÍ TANTO COMO EL QUTB, EN SU CELESTIAL LATĪFA KHAFIYYA, DETERMINE PRUDENTE TORTURARLO ANTE LA SÉPTIMA PUERTA DEL BARZAJ. ABRAXAS HA DICHO QUE LE DA IGUAL SIEMPRE QUE SE LO MANTENGAN DISOCIADO DEL PLEROMA EN TRANSITO INDETERMINADO POR EL KENOMA. ALGUNOS ILUMINADOS DEL CICLO 33 HAN SUGERIDO SE LE ATROPELLLE CON EL MERKABÁ POR LA ETERNIDAD. LAS DIEZ SEFIROT DELIBERAN SI APROXIMAR LA PIEDRA DE SEFER RAZIEL AL CULTO ANÁNKE DE SU FATALIDAD.",
    "AUTEM, EL COLAPSO INMINENTE DE LOS TÚNELES DE SET & LA TRASPOSICIÓN TOHU-BOHU DEL SENDERO DE SAMAEL (AMÉN DE EXARP–HCOMA–NANTA–BITOM), HA EMPUJADO AL TRIUNVIRATO SHEVIRAT HA-KELIM/SHEM HA-MEPHORASH/MALKUTH-ATZILUT A TOMAR UNA DECISIÓN EÓNICA ENTINTADA EN LA URDIMBRE CAUSAL DEL DESTINO DE ZEVAXTIANS. ",
    "# DE NO CONSAGRAR SUS OBLIGACIONES CON EL ÁNGULO ANARETICO, SE DARÁ VIA LIBRE AL LATIDO HERMÉTICO DEL NOMBRE IMPRONUNCIABLE, & SE PROCEDERÁ A DISOLVER FULMINANTEMENTE LAS ASTILLAS DE SU EXISTENCIA ANTE LA NOCHE DE YESOD."
]